//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookahMvcBookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBook
    {
        public tblBook()
        {
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public int BookId { get; set; }
        public string Author { get; set; }
        public string Description { get; set; }
        public string Edition { get; set; }
        public string ISBN { get; set; }
        public string Publisher { get; set; }
        public string Picture { get; set; }
        public string Title { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> CatId { get; set; }
    
        public virtual tblCategory tblCategory { get; set; }
        public virtual ICollection<tblOrder> tblOrders { get; set; }
    }
}
