//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookahMvcBookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public tblOrder()
        {
            this.tblInvoices = new HashSet<tblInvoice>();
        }
    
        public int OrderId { get; set; }
        public Nullable<int> BookId { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Total { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string PayMethod { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual tblBook tblBook { get; set; }
        public virtual ICollection<tblInvoice> tblInvoices { get; set; }
        public virtual tblUser tblUser { get; set; }
    }
}
