//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookahMvcBookApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public tblUser()
        {
            this.tblInvoices = new HashSet<tblInvoice>();
            this.tblOrders = new HashSet<tblOrder>();
        }
    
        public int UserId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleType { get; set; }
        public Nullable<int> IDNumber { get; set; }
    
        public virtual ICollection<tblInvoice> tblInvoices { get; set; }
        public virtual ICollection<tblOrder> tblOrders { get; set; }
    }
}
